language: node_js
node_js:
  - "4"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g gulp-cli
after_success : gulp build
notifications:
  email: false
  irc: "chat.freenode.net#butterdev"
